import type { Metadata } from "next";
import { Inter, Roboto_Mono } from "next/font/google";
//import localFont from "next/font/local";
import "./globals.css";
import Header from "./components/header";
import Link from "next/link";
import { AntdRegistry } from "@ant-design/nextjs-registry";

const interSans = Inter({
  variable: "--font-inter-sans",
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: "--font-roboto-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "NextJS App",
  description: "Generated by create next app",
  icons: {
    icon: [
      {
        url: "/favicon-16x16.png",
        href: "/favicon.ico",
        sizes: "16x16",
        type: "image/png",
      },
      { url: "/favicon-32x32.png", sizes: "32x32", type: "image/png" },
    ],
    shortcut: "/shortcut.ico",
    apple: "/apple-touch-icon.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${interSans.variable} ${robotoMono.variable} antialiased`}
      >
        <Header />
        <div className="absolute top-0 left-0">
          <div className="bg-red-500">
            <Link href="/performance">Performance</Link>
            <Link href="/reliability">Reliability</Link>
            <Link href="/scale">Scale</Link>
            <AntdRegistry>{children}</AntdRegistry>
          </div>
        </div>
      </body>
    </html>
  );
}
